ALTER TABLE food_items
    ADD COLUMN IF NOT EXISTS sugar FLOAT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fiber FLOAT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS hdl_support_score FLOAT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS triglyceride_risk_weight FLOAT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS food_group VARCHAR(30) NOT NULL DEFAULT 'general',
    ADD COLUMN IF NOT EXISTS high_carb_flag BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS nut_seed_exception BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE daily_logs
    ADD COLUMN IF NOT EXISTS total_sugar FLOAT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_fiber FLOAT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_hdl_support FLOAT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_triglyceride_risk FLOAT NOT NULL DEFAULT 0;

ALTER TABLE metabolic_agent_state
    ADD COLUMN IF NOT EXISTS fruit_allowance_weekly INTEGER NOT NULL DEFAULT 7;
