ALTER TABLE daily_logs
    ADD COLUMN IF NOT EXISTS dinner_meal JSON NULL,
    ADD COLUMN IF NOT EXISTS dinner_mode VARCHAR(20) NULL,
    ADD COLUMN IF NOT EXISTS dinner_logged_at TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS dinner_insulin_impact FLOAT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS evening_insulin_spike_risk BOOLEAN NOT NULL DEFAULT FALSE;
